# This file tells Travis what's up
language: node_js
node_js:
- stable

notifications:
  email: false

before_install:
- npm i -g yarn

# When Travis gets notified of a new build, do this
script: 
- yarn ci
